apiVersion: v1
kind: Service
metadata:
  name: rockcom-backend-service-dev
spec:
  selector:
    app: rockcom-backend-dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP