apiVersion: apps/v1
kind: Deployment
metadata:
  name: rockcom-backend-dev
  labels:
    app: rockcom-backend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rockcom-backend-dev
  template:
    metadata:
      labels:
        app: rockcom-backend-dev
    spec:
      containers:
        - name: rockcom-backend-dev
          image: 329976954374.dkr.ecr.eu-central-1.amazonaws.com/rockcom/backend-dev:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: deployment
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SPRING_DATASOURCE_PASSWORD

      imagePullSecrets:
        - name: aws-ecr-secret

#kubectl create secret generic db-secret \
#--from-literal=SPRING_DATASOURCE_URL=${{ secrets.DB_URL }} \
#--from-literal=SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
#--from-literal=SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \