services:
  rockcom-db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rockcom-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: