apiVersion: apps/v1
kind: Deployment
metadata:
  name: rockcom-frontend
  labels:
    app: rockcom-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rockcom-frontend
  template:
    metadata:
      labels:
        app: rockcom-frontend
    spec:
      containers:
        - name: rockcom-frontend
          image: 329976954374.dkr.ecr.eu-central-1.amazonaws.com/rockcom/frontend:1bcf288c803cde2e1f40c3794435b4f2b688164a
          ports:
            - containerPort: 3000